# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request 
# events but only for the master branch
on:
  push:
    branches: [ staging ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Webhook
      uses: joelwmale/webhook-action@master
      env:
        WEBHOOK_URL:  https://dynamic.hosting.coronadenktank.be:8443/modules/git/public/web-hook.php?uuid=4ffa76ff-1329-a09e-cd43-799a989ed872 
        data: "{'deployment': 'finished', 'project': 'actions'}"
